[colors.primary]
background = '#0d1518'
foreground = '#dbe4e8'

[colors.cursor]
text = '#3e2e00'
cursor = '#e9c261'

[colors.vi_mode_cursor]
text = '#0d1518'
cursor = '#e9c261'

[colors.search.matches]
foreground = '#3b494f'
background = '#93cfe7'

[colors.search.focused_match]
foreground = '#3b494f'
background = '#e9c261'

[colors.footer_bar]
foreground = '#3b494f'
background = '#dbe4e8'

[colors.hints.start]
foreground = '#3b494f'
background = '#cdc0e9'

[colors.hints.end]
foreground = '#3b494f'
background = '#cdc0e9'

[colors.selection]
text = '#0d1518'
background = '#e9c261'

[colors.normal]
black = '#0d1518'
red = '#ffb4ab'
green = '#e9c261'
yellow = '#765a00'
blue = '#e9c261'
magenta = '#93cfe7'
cyan = '#cdc0e9'
white = '#dbe4e8'

[colors.bright]
black = '#3b494f'
red = '#93000a'
green = '#594400'
yellow = '#4b4263'
blue = '#004d61'
magenta = '#e9ddff'
cyan = '#e9c261'
white = '#bac9d0'

[colors.dim]
black = '#070f12'
red = '#93000a'
green = '#e9c261'
yellow = '#765a00'
blue = '#594400'
magenta = '#93cfe7'
cyan = '#cdc0e9'
white = '#3b494f'
